In [1]:
!pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/294.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/294.9 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/294.9 kB 325.1 kB/s eta 0:00:01
   ---- ---------------------------------- 30.7/294.9 kB 32


[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
#SVM on TITANIC DATASET
#import libraries
import numpy as np
import pandas as pd
import seaborn as sb

In [12]:
titanic = sb.load_dataset('titanic')

In [13]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [14]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [15]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [16]:
titanic['age'].dtypes

dtype('float64')

In [17]:
titanic['age'].isnull().sum()

np.int64(177)

In [18]:
#replace missing age with mean
titanic['age'].fillna(titanic['age'].mean(),inplace=True)

C:\Users\Deepika\AppData\Local\Temp\ipykernel_15988\65112551.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['age'].fillna(titanic['age'].mean(),inplace=True)


In [19]:
titanic['age'].isnull().sum()

np.int64(0)

In [20]:
#embraked
titanic['embarked'].isnull().sum()

np.int64(2)

In [21]:
titanic['embarked'].dtypes

dtype('O')

In [22]:
#embarked
titanic['embarked'].fillna(titanic['embarked'].mode()[0],inplace = True)

C:\Users\Deepika\AppData\Local\Temp\ipykernel_15988\2995522172.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['embarked'].fillna(titanic['embarked'].mode()[0],inplace = True)


In [24]:
titanic['embarked'].isnull().sum()

np.int64(0)

In [25]:
#handle deck
titanic['deck'].dtypes

CategoricalDtype(categories=['A', 'B', 'C', 'D', 'E', 'F', 'G'], ordered=False, categories_dtype=object)

In [26]:
titanic['deck'].fillna(titanic['deck'].mode()[0],inplace=True)

C:\Users\Deepika\AppData\Local\Temp\ipykernel_15988\95445592.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['deck'].fillna(titanic['deck'].mode()[0],inplace=True)


In [27]:
titanic['deck'].isnull().sum()

np.int64(0)

In [28]:
titanic['embark_town'].dtypes

dtype('O')

In [30]:
titanic['embark_town'].fillna(titanic['embark_town'].mode()[0],inplace = True)

C:\Users\Deepika\AppData\Local\Temp\ipykernel_15988\1265623134.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['embark_town'].fillna(titanic['embark_town'].mode()[0],inplace = True)


In [31]:
titanic['embark_town'].isnull().sum()

np.int64(0)

In [32]:
titanic.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [33]:
titanic

survived  pclass     sex        age  sibsp  parch     fare embarked  \
0           0       3    male  22.000000      1      0   7.2500        S   
1           1       1  female  38.000000      1      0  71.2833        C   
2           1       3  female  26.000000      0      0   7.9250        S   
3           1       1  female  35.000000      1      0  53.1000        S   
4           0       3    male  35.000000      0      0   8.0500        S   
..        ...     ...     ...        ...    ...    ...      ...      ...   
886         0       2    male  27.000000      0      0  13.0000        S   
887         1       1  female  19.000000      0      0  30.0000        S   
888         0       3  female  29.699118      1      2  23.4500        S   
889         1       1    male  26.000000      0      0  30.0000        C   
890         0       3    male  32.000000      0      0   7.7500        Q   

      class    who  adult_male deck  embark_town alive  alone  
0     Third    man        True    C  Southampton    no  False  
1     First  woman       False    C    Cherbourg   yes  False  
2     Third  woman       False    C  Southampton   yes   True  
3     First  woman       False    C  Southampton   yes  False  
4     Third    man        True    C  Southampton    no   True  
..      ...    ...         ...  ...          ...   ...    ...  
886  Second    man        True    C  Southampton    no   True  
887   First  woman       False    B  Southampton   yes   True  
888   Third  woman       False    C  Southampton    no  False  
889   First    man        True    C    Cherbourg   yes   True  
890   Third    man        True    C   Queenstown    no   True  

[891 rows x 15 columns]

In [34]:
#DATA CONVERSION
from sklearn.preprocessing import LabelEncoder

In [36]:
le = LabelEncoder()

In [37]:
titanic.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [38]:
#convert sex attributes values to numeric
titanic['sex'] = le.fit_transform(titanic['sex'])

In [39]:
titanic['sex']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: sex, Length: 891, dtype: int64

In [40]:
#convert sex attributes values to numeric
titanic['embarked'] = le.fit_transform(titanic['embarked'])
titanic['class'] = le.fit_transform(titanic['class'])
titanic['deck'] = le.fit_transform(titanic['deck'])
titanic['embark_town'] = le.fit_transform(titanic['embark_town'])
titanic['alive'] = le.fit_transform(titanic['alive'])
titanic['alone'] = le.fit_transform(titanic['alone'])
titanic['who'] = le.fit_transform(titanic['who'])

In [41]:
titanic

survived  pclass  sex        age  sibsp  parch     fare  embarked  class  \
0           0       3    1  22.000000      1      0   7.2500         2      2   
1           1       1    0  38.000000      1      0  71.2833         0      0   
2           1       3    0  26.000000      0      0   7.9250         2      2   
3           1       1    0  35.000000      1      0  53.1000         2      0   
4           0       3    1  35.000000      0      0   8.0500         2      2   
..        ...     ...  ...        ...    ...    ...      ...       ...    ...   
886         0       2    1  27.000000      0      0  13.0000         2      1   
887         1       1    0  19.000000      0      0  30.0000         2      0   
888         0       3    0  29.699118      1      2  23.4500         2      2   
889         1       1    1  26.000000      0      0  30.0000         0      0   
890         0       3    1  32.000000      0      0   7.7500         1      2   

     who  adult_male  deck  embark_town  alive  alone  
0      1        True     2            2      0      0  
1      2       False     2            0      1      0  
2      2       False     2            2      1      1  
3      2       False     2            2      1      0  
4      1        True     2            2      0      1  
..   ...         ...   ...          ...    ...    ...  
886    1        True     2            2      0      1  
887    2       False     1            2      1      1  
888    2       False     2            2      0      0  
889    1        True     2            0      1      1  
890    1        True     2            1      0      1  

[891 rows x 15 columns]

In [42]:
#DATA SEPRATION
Y = titanic['survived']

In [43]:
Y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [44]:
X = titanic.drop(['survived'],axis = 1)

In [45]:
X

pclass  sex        age  sibsp  parch     fare  embarked  class  who  \
0         3    1  22.000000      1      0   7.2500         2      2    1   
1         1    0  38.000000      1      0  71.2833         0      0    2   
2         3    0  26.000000      0      0   7.9250         2      2    2   
3         1    0  35.000000      1      0  53.1000         2      0    2   
4         3    1  35.000000      0      0   8.0500         2      2    1   
..      ...  ...        ...    ...    ...      ...       ...    ...  ...   
886       2    1  27.000000      0      0  13.0000         2      1    1   
887       1    0  19.000000      0      0  30.0000         2      0    2   
888       3    0  29.699118      1      2  23.4500         2      2    2   
889       1    1  26.000000      0      0  30.0000         0      0    1   
890       3    1  32.000000      0      0   7.7500         1      2    1   

     adult_male  deck  embark_town  alive  alone  
0          True     2            2      0      0  
1         False     2            0      1      0  
2         False     2            2      1      1  
3         False     2            2      1      0  
4          True     2            2      0      1  
..          ...   ...          ...    ...    ...  
886        True     2            2      0      1  
887       False     1            2      1      1  
888       False     2            2      0      0  
889        True     2            0      1      1  
890        True     2            1      0      1  

[891 rows x 14 columns]

In [46]:
#DATA SPLITTING
from sklearn.model_selection import train_test_split

In [47]:
#70 % training and 30% testing
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3)

In [48]:
X_train.shape

(623, 14)

In [49]:
X_test.shape

(268, 14)

In [50]:
Y_train.shape

(623,)

In [51]:
Y_test.shape

(268,)

In [52]:
#model selection - LINEAR SVM
from sklearn.svm import SVC

In [53]:
lin_svm = SVC()

In [54]:
#model training
lin_svm.fit(X_train,Y_train)

SVC()

In [55]:
#model prediction
lin_svm_pred = lin_svm.predict(X_test)

In [56]:
lin_svm_pred

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0])

In [58]:
from sklearn.metrics import accuracy_score

In [60]:
print("accuracy score of linear svm ",accuracy_score(Y_test,lin_svm_pred)*100)

accuracy score of linear svm  66.7910447761194


In [61]:
from sklearn.metrics import confusion_matrix

In [62]:
print("confusion matrix of linear svm \n",confusion_matrix(Y_test,lin_svm_pred))

confusion matrix of linear svm 
 [[145  13]
 [ 76  34]]


In [65]:
#2nd model polynomial svm
poly_svm=SVC(kernel = 'poly')

In [66]:
poly_svm.fit(X_train,Y_train)

SVC(kernel='poly')

In [68]:
poly_pred = poly_svm.predict(X_test)

In [69]:
poly_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0])

In [70]:
print("accuracy of polynomial svm",accuracy_score(Y_test,poly_pred)*100)

accuracy of polynomial svm 63.80597014925373


In [71]:
print("confusion matrix \n",confusion_matrix(Y_test,poly_pred))

confusion matrix 
 [[156   2]
 [ 95  15]]


In [75]:
rdf = SVC(kernel = 'rbf')

In [76]:
rdf.fit(X_train,Y_train)

SVC()

In [77]:
rdf_pred = poly_svm.predict(X_test)

In [79]:
rdf_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0])

In [82]:
print("accuracy of rbf svm",accuracy_score(Y_test,rdf_pred)*100)

accuracy of rbf svm 63.80597014925373


In [83]:
print("confusion matrix \n",confusion_matrix(Y_test,rdf_pred))

confusion matrix 
 [[156   2]
 [ 95  15]]
